### ISSUE TITLE
Akka Version 2.7.0 Memory leak?

### ISSUE THREAD

**Issue by USHPINDER** [akka/akka-persistence-cassandra#1043]
I'm using Akka actor system with version 2.7.0 and we are facing memory leak issue as below:

When the process gets completed, heap memory is not getting free and below are two potential causes:

![image](https://github.com/akka/akka/assets/90985835/c3e56cea-13aa-4387-95d0-a742b70df050)

**Comment by johanandren** [comment]
TagWriter is on the writing side of the journal specifically in akka-persistence-cassandra, so moving the issue over there

**Comment by johanandren** [comment]
Also, if you are a Lightbend customer, please raise a parallel issue in the support portal for more urgent help.

**Comment by USHPINDER** [comment]
@johanandren 
On further analysis we figure it out that for clean up we have used deleteAll which was causing this leak...Can you suggest something?
![image](https://github.com/akka/akka-persistence-cassandra/assets/90985835/40d2754e-395d-4640-b314-3bf09ffc1a1a)

With deleteAllTaggedEvents

![MicrosoftTeams-image (41)](https://github.com/akka/akka-persistence-cassandra/assets/90985835/637ee8a1-5fce-45e7-bc5c-eb8f176edf9c)


With deleteAllTaggedEvents

 
![MicrosoftTeams-image (42)](https://github.com/akka/akka-persistence-cassandra/assets/90985835/0d305f22-5053-49f6-87f5-8020dc00f7f9)

**Comment by johanandren** [comment]
That should still not create many journals, the TagWriterSession are 1:1 with journal instances, so 250k of those indicate that there is something not quite right. The normal case is 1 or a few journals per actor system (and one actor system per JVM). 

Are you using `RuntimePluginConfig` for dynamic configuration of journals or some other out of the ordinary when setting up your entities/the cleanup tool?

**Comment by USHPINDER** [comment]
@johanandren 
We are using basic deleteAll only and there is only one journal per actor system and one actor system per JVM:
![image](https://github.com/akka/akka-persistence-cassandra/assets/90985835/b5c75324-a8de-4fee-b6f9-08af2088c7bc)
Below are basic settings:
![image](https://github.com/akka/akka-persistence-cassandra/assets/90985835/726540b7-893f-4578-a785-8f423859b007)

**Comment by johanandren** [comment]
And you re-use the same instance of Cleanup across deletes?

**Comment by USHPINDER** [comment]
@johanandren 
We are using one instance per Actor and calling delete only once just after passivate and before thenStop().

Below is flow:

```
Efftect<Event,State> onPoisionPill{
 return Effect()
                .none()
                .thenRun(
                        () -> {
                            shard.tell(new ClusterSharding.Passivate<>(context.getSelf()));
                            Cleanup cleanup = new Cleanup(context.getSystem());
                           cleanup.deleteAll("xyz", false);
                        })
                .thenStop();
}
```

**Comment by johanandren** [comment]
You should create a single instance of `Cleanup` per actor system and share/inject to your sharded entities rather than use one per entity. Creating many of them is the reason why you end up with one `TagWriter` actor leaking per delete.

Note that how you are using it is not really what the `Cleanup` tool was made for. The docs on the tool explicitly says that an actor with a given pid must not be running at the same time as the tool is run, but in your case it is not stopped yet.

In general a safe delete design would be to not actually delete until quite some time after an entity has been marked for deletion. For example through a projection consuming the tombstone markers, keeping track of seen deleted entities and then after a grace period have a cleanup job doing the actual deletes. 

The reason is that projections may not have consumed all events for that entity yet and you can miss events as they were deleted before seen by projections. It is also important make sure you understand the consequences of frequent deletes vs Cassandra itself and tombstones/compaction.

**Comment by USHPINDER** [comment]
With single instance of cleanup tool, we are able to successfully use deleteAll without TagWriter actor leakage.
