### ISSUE TITLE
Browsable event journal

### ISSUE THREAD

**Issue by patriknw** [akka/akka-persistence-cassandra#12]
Originally reported by @magnusart in https://github.com/krasserm/akka-persistence-cassandra/issues/50

**Comment by magnusart** [comment]
I propose that this issue is closed.

Since this issue was opened some two things have happened:
- Custom seralizers that can seralize to strings (Json) not only object
- Akka persistence query moving along

This means that some more alternatives are available than previously. 

I can now choose to store my events as Json in Cassandra (for example using Scala Pickling to avoid the runtime penalty) and use any Cassandra compatible DB Browser to view and hopefully query my data.

Akka persistence query in turn could be used for creating tooling that can do ad-hoc queries for any journal, regardless of storage engine. As I imagine that this would be useful for other journals as well I think that belongs in the Akka persistence query project or in a new project that depends on akka persistence query. 

It would be _awesome_ if Typesafe looked into tooling for akka persistence, but I suspect you have a lot on your plate already.

**Comment by patriknw** [comment]
I don't think you can currently use "any Cassandra compatible DB Browser" to browse the events, because that tool doesn't know how to deserialize the PersistentRepr.

I would like to do not store the PersistentRepr as a serialized blob, but add additional columns and only only store the event as a blob. I think that can be done in a backwards compatible way, but wanted to mention it here also.

**Comment by magnusart** [comment]
Right, I had to go into the code and look it up. I was under the impression that this was already the case. Now enlightened, I agree that with what you wrote, it is not as easy as I hoped.

As it is now not being able to ad-hoc browse/query data during debugging, incidents, customer support etc is a very limiting factor. 

I'd really like for this issue to be resolved in a general fashion with Akka persistence queries, but it's a challenge to build a general tool since you need to provide your data model and (de)serializer.

I'm a bit out of ideas actually. Closest I can come up with is perhaps creating an Sbt plugin that you add to your projects where you can query/monitor via Akka persistence query. Other ideas welcome!

**Comment by patriknw** [comment]
Don't we come a long way by storing the event blob (possibly JSON bytes) in a separate column? Then you can use standard tools to select and inspect the events.

I mean, it will of course not be possible to select events based on the data inside the events (arbitary ad-hoc queries). For that you need to create a read-side projection of the events that is indexed in a way that supports the required queries. That is already possible at the application level, and it belongs there since it is very application specific.

**Comment by sebastiaansamyn-tc** [comment]
I concur with @patriknw, putting the event in its own column solves 90% of the problem. Once that's present, utilities can be built on top of it, because now that's not really possible. 

What I did on our current project was to write a utility that reads the event stream for a PersistentActor and just prints out all the events. It's useful for debugging, but pointless for anything else.

**Comment by magnusart** [comment]
Alright, so what would be the plan be for managing the switchover to a new schema and what will happen with the old data? 

1. Expand the schema to the least common denominator so it can handle both the new fields while maintaining backwards compatibility with the old structure
2. Akka persistence would force a migration of data to be persisted into the new schema?

The second option would be the cleanest to work with going forwards. But to me it also feels quite risky, many things that could go bad when migrating a whole datastore.

**Comment by patriknw** [comment]
For this one I think we can do it in a backwards compatible way, old events are read by the `message` column (serialized PersistentRepr) and new events are read by new columns (`message` column is null).

I have started working on this, by the way.

**Comment by magnusart** [comment]
Aha, cool. I was thinking about looking into it because I was curious and it seemed like a good segway into the codebase. Tell me if I can help. :)

**Comment by patriknw** [comment]
@magnusart it would be great if you can complete what I have started. Pushed my current state here: https://github.com/akka/akka-persistence-cassandra/pull/21
We can discuss in the PR. E.g. of missing things:
* verify that it really works :-)
* verify backwards compatibility, i.e. populate data with old version and then switch over
* add notes about migration
* see if we can do the same for snapshots

**Comment by magnusart** [comment]
Sure, I'll have a look.

**Comment by magnusart** [comment]
@patriknw I had a quick look and started thinking about how to verify that it really works. I'd really like to have a test for it since it would be *very* time consuming to go back and forth when debugging issues related to the migration if I have to do the migartion manually each time.

**I'm considering the following approach:** take one of the snapshot tests and pause it just before it exits, export the data from Cassandra tables and use that as a base for a DB-script that would populate the Cassandra test database at the beginning of the migration test and the proceed to test migration and persisting new events. 

Would that cover it? suggestions welcome! 

The only extra scenario I can come up with is that the user moves back and forth between versions after recording data. But I cannot judge yet if that would make any difference, are we forwards compatible as well?
