### ISSUE TITLE
CassandraSession.close and async vs sync

### ISSUE THREAD

**Issue by johanandren** [akka/akka-persistence-cassandra#135]
The close method will call closeAsync on the underlying session but is itself a`() => Unit` method and does not block on the underlying async closing. Could we return a Future[Done] instead to allow users to react on close completion?

Reported in gitter by @fabienbk running into problems when running on top of Tomcat:

> It's causing some race conditions when destroying a webapp in tomcat, because tomcat servletcontext classloader shuts down faster than the closeAync() completion
> and then tomcat freezes in an incoherent states (some non-daemon thread still lingering)

**Comment by patriknw** [comment]
We can return Future, but we will not wait for it to complete in the journal and snapshot actors, because that would mean blocking in those actors' `postStop`. In other words, it will probably not help for the Tomcat case.

Additionally, we don't guarantee that all Akka threads have been stopped when the actor system has been terminated. E.g. if you have a Future callback with the ActorSystem's dispatcher that will wake up the thread pool again (followed by later shutdown).

**Comment by johanandren** [comment]
Maybe not worth doing anything then?

**Comment by patriknw** [comment]
It doesn't hurt to add the return value and it can be used by those who create their own `CassandraSession`.

**Comment by fabienbk** [comment]
@patriknw : do you mean it's possible to subclass `CassandraSession` ?

**Comment by patriknw** [comment]
No, I mean that it's possible to create own instance of it and when used like that it can useful with the Future return value

**Comment by patriknw** [comment]
@notxcain May I ask you to fix this also? :)

**Comment by notxcain** [comment]
@patriknw I must have missed a notification. I will send a PR. Also I have a feedback about usage of CassandraSession, should we discuss it on gitter?

**Comment by fabienbk** [comment]
Hi there, was it finally fixed ? or did it become irrelevant ?

**Comment by patriknw** [comment]
Previously it was closed from `postStop` of journal actor, but that has now been removed and the sessions are now closed automatically by the session registry when the ActorSystem has been terminated. That is done async, without waiting for it to complete.
