### ISSUE TITLE
Remove 3 tags per event limit

### ISSUE THREAD

**Issue by Tvaroh** [akka/akka-persistence-cassandra#218]
I wonder if 3 tag per event limit can be removed.

What if to store events in Cassandra `set` field instead of 3 separate fields for each tag? The number of materialized views can become large (equal to distinct tags number), but that can be manageable. Are there any problems with this approach?

In my use case, I want a potentially unlimited number of tags per event, so any inputs are welcome.

**Comment by patriknw** [comment]
The reason is exactly that I think there is quite a lot of overhead (work for Cassandra) to keep the materialized views updated. The materialized view is also rather restricted in what kind of fields that are supported. Not sure collection fields are supported.

Could you describe the use case some more and I'll see if I have any advice.

**Comment by Tvaroh** [comment]
Sure, thanks.

For each event I need to maintain a list of users it does affect to be able to notify them. For example a user can share its data to other users, so when it modifies it, I calculate the affected users, and want to be able to notify them immediately (by sending WebSocket message) or when they come online. I was thinking about tagging each event with users ids it affects and then use `EventsByTag` to get a "changeline" for each specific user.

**Comment by Tvaroh** [comment]
Btw, I just checked in Cassandra shell: creating a materialized view that includes `set<text>` field does work.

**Comment by patriknw** [comment]
There is another problem with your design. You would have one active query stream for each user. That doesn't scale well, because each such query will poll Cassandra for new events. It's better that you have one tag (or a few tags) and one (or a few) active query and then route the events to the web sockets when consuming the events.

Note that the primary purpose of the event queries are to build up read side views that can be used for specific end user queries. They are not intended to serve end user queries directly.

**Comment by Tvaroh** [comment]
> It's better that you have one tag (or a few tags) and one (or a few) active query and then route the events to the web sockets when consuming the events.

I see, thanks. How about the offline case, when I need to find user-related events and send them to the client when he comes online? Do you suggest to maintain such a view manually by consuming the events and building up query side I need for my use case?

**Comment by patriknw** [comment]
> Do you suggest to maintain such a view manually by consuming the events and building up query side I need for my use case?

Yes, I would do it like that. Perhaps a mix. Fetching "current state" from the view and then get live events with the stream.

**Comment by Tvaroh** [comment]
Okay, thanks. Feel free to close this issue if you think that 3 tags limit is a reasonable choice and shouldn't be removed. Though, I can't see any problems with implementing unlimited tags number support besides backwards compatibility and understanding the consequences of having potentially a lot of materialized views.
