### ISSUE TITLE
High eventsByTag latency when empty time buckets are present

### ISSUE THREAD

**Issue by olivierdeckers** [akka/akka-persistence-cassandra#347]
When a certain persistence id generates some messages, then nothing for one or more timebuckets, and then a new message is persisted, the persistence plugin will always wait for the configured gap-timeout before the stream starts returning results.

This is because it only looks at the current and the previous timebucket, even if it is empty, so it will never see the "missing" events.

I included some logs illustrating the problem:
[akka-persistence-cassandra-logs.txt](https://github.com/akka/akka-persistence-cassandra/files/1970360/akka-persistence-cassandra-logs.txt)

**Comment by chbatey** [comment]
Thanks for reporting @olivierdeckers i'll take a look at this

**Comment by brettdaman** [comment]
+1

**Comment by nicovanlooy** [comment]
+1

**Comment by kevinverelst** [comment]
+1

**Comment by intergalactic-overlords** [comment]
+1

**Comment by Anntje** [comment]
+1

**Comment by chbatey** [comment]
What behaviour would you like to see? There's always a chance that a query could see sequence nr N+1 for a new persistenceId before seeing N.

The gap-timeout is currently used for times we definitely know there is a gap because we've seen the persistenceId previously and for new persistenceIds. 

I can't think of a usecase where you'd want to not look for a missing sequenceNr for a known persitesnceId as we know for sure we've missed an event. 

Perhaps we should use a different timeout for new persitenceIds and if you set it to 0 then it assumes that this is the right sequence nr.

**Comment by olivierdeckers** [comment]
I think the problem is caused by the fact that an entity is considered 'new', while it actually isn't. The log file I added in the issue contains the following line: 

> "Tag4: Missing event for new persistence id: Entity1. Expected sequence nr: 1, actual: 328."

Entity1 is not a new entity, so it is strange that the expected sequence number is 1. How is this sequence number calculated? Is it retrieved from the tag_views table?

**Comment by chbatey** [comment]
New here means it is the first time that this events by tag query has seen it. 

The sequence nr is per tag/pid combination to guarantee ordering per pid.

For offset queries that start in the current tie bucket we don't know what the first tag pid sequence nr should be. We try to work it out at the start of the query by finding the tag/pid sequence nrs in the current bucket but in this case the pid had no events in the current bucket so it looks for a while when it gets the first event.

**Comment by olivierdeckers** [comment]
@chbatey Thanks for the PR! 

It is not entirely clear to me what the risks are of setting this new config parameter to zero or a low value. The documentation says the stage will fail if events are returned out of order. When is this detected? Does the stream fail before or after the out-of-order events can be read from it?

I am also wondering if it is possible to use the information in the tag_views table to solve this and at the same time avoid depending on a sufficiently high timeout. If we know from the tag_views table that  an offset larger than the one we currently encounter (328 in the example) has been written, then the write hasn't happened very recently and there is no need for a timeout?

**Comment by chbatey** [comment]
The risk would be that a delayed event with a timestamp greater than the offset is delayed somehow and we get a newer event and assume that is the first we will see and deliver it.

I don't think there being an event with a greater offset rules out the above delayed event. Because isolation doesn't exist in Cassandra we can always see them out of order. Once we've seen a persistenceId during a query we know for sure which tag_pid_sequence_nr we should be getting next but for the first time a persistence_id comes back it is always a bit of guess work.

**Comment by chbatey** [comment]
Closing this as i've released a version with the additional timeout. If you can think of any other improvements or a scenario where the latency is high feel free to re-open or raise a new issue.
