### ISSUE TITLE
API For deleting tagged events

### ISSUE THREAD

**Issue by nvollmar** [akka/akka-persistence-cassandra#378]
After deleting all events from a persistent actor (through deleteMessages) they are still recovered through tagged persistence queries.

Delete should (eventually) delete them from the tag views too.

**Comment by patriknw** [comment]
That should be discussed. Having the tagged view detached has benefits. For example, a rather common case is that you use snapshots on the write side and delete events before the snapshots. That doesn't mean that events can automatically be deleted from the read side since that might not have consumed the events yet or consumption is detached (should be possible much later by new consumers).

I think I'd prefer an explicit separate API for deleting in tagged view.

**Comment by nvollmar** [comment]
Or some functionality to rebuild tagged views on demand would also be sufficient for us

**Comment by chbatey** [comment]
Let's leave this open for having an API for deleting tagged events. I'll create a separate ticket for having the ability to rebuild the tags view which has quite a few uses e.g. tag_view table being corrupted after a split brain.

**Comment by chbatey** [comment]
I think the deletion of events shouldn't be allowed to leave gaps in the tag pid sequence numbers, so it should only be able to delete all the events for a persistence id a subset from the beginning

**Comment by nvollmar** [comment]
We're currently only deleting all events for a persistence id (but I think there is no api to completely get rid of the persistence id/sequence number)

**Comment by patriknw** [comment]
This is supported by the new reconciler tool
