### ISSUE TITLE
Reconnect to Cassandra after IP address changes

### ISSUE THREAD

**Issue by ennru** [akka/akka-persistence-cassandra#445]
### Short description

Especially when running Cassandra in Kubernetes a pod restart will change Cassandra's IP address. Could Akka Persistence Cassandra make a new service lookup when that happens?

### Details

_Added by @TimMoore 18 Apr 2019_

There are a few layers to the problem.

Lagom interfaces with Akka Persistence Cassandra by implementing a custom `SessionProvider` that looks up the Cassandra contact points in the `ServiceLocator` (essentially a DNS SRV query in Kubernetes) and uses the results to build the Cassandra `Session`. That means that by the time the driver is initialized, it is getting a list of resolved `InetSocketAddress` instances (essentially IP:port pairs).

Kubernetes `StatefulSet` does not have the ability to reuse IPs of deleted pods when replacing them (https://github.com/kubernetes/kubernetes/issues/28969). This means that after a shutdown and restart of the Cassandra cluster, the IP addresses that the Cassandra `Session` was built with are stale.

`StatefulSet` pods _do_ have stable host names, but using these doesn't help, either, because the Cassandra driver caches the resolved addresses internally ([JAVA-1522](https://datastax-oss.atlassian.net/browse/JAVA-1522)). Version 4.0 of the driver offers an option to store the unresolved addresses ([JAVA-1978](https://datastax-oss.atlassian.net/browse/JAVA-1978)) if the `Session` is created that way.

We are planning to refactor the session management in Akka Persistence Cassandra by extracting that to Alpakka Cassandra. As part of that work, we also want to integrate support for Akka Service Discovery directly, so that Lagom can use that in the future, and everyone else using Alpakka Cassandra or Akka Persistence Cassandra can also get automatic discovery. However, it will experience the same problem unless we make other changes.

In Akka Persistence Cassandra, once it builds a `Session`, it keeps it and reuses it forever, so AFAICT the only way to get it to re-resolve is to restart the `ActorSystem` (effectively requiring a full service restart in Lagom). Without doing a detailed investigation, I think the cleanest way to solve all of this would be to change our `CassandraSession` wrapper to (optionally?) detect `NoHostAvailableException` failures in the underlying session, then dispose and recreate the session from the `SessionProvider` (and retry executing the statement?)

**Comment by patriknw** [comment]
Isn’t it handled by the connection pool in the driver?

**Comment by patriknw** [comment]
You mean that it is a problem when the entire Cassandra cluster is restarted, with new IP adresses?

**Comment by TimMoore** [comment]
That’s right @patriknw

**Comment by dpennell** [comment]
note that this can happen over time.  i.e. if all of the nodes in the cassandra cluster are restarted one at a time, all services will lose connectivity with the cassandra cluster and have to be restarted.

**Comment by patriknw** [comment]
I thought that the driver would exchange contact points with the servers to be able to use new nodes for re-connects (as long as not the entire cluster is restarted at once), but that’s only my assumption without knowing. Anyway, that would also be solved by this.

**Comment by chbatey** [comment]
This sounds like a problem with the driver for when nodes come back with a different IP but are replacing an existing host id. Perhaps raise upstream? Also, include details of how Cassandra is being deployed in Kubernetes.

**Comment by dpennell** [comment]
@patriknw I also assumed that the driver would learn of node changes, but that does not match observations.
@chbatey cassandra was deployed using https://github.com/helm/charts/tree/master/incubator/cassandra with 3 replicas.  Lagom services pointed at the cassandra statefulSet created by this helm chart.  We first noticed the issue when running low on resources and having cassandra pods regularly restarted.  Logs show continued attempts to use the initial set of 3 pods IP's and this never changes.  Let me know if you need more details.

**Comment by TimMoore** [comment]
Sorry, @ennru jotted this down after a quick in-person conversation, but I can add some more context to this. There are a few layers to the problem.

Lagom interfaces with Akka Persistence Cassandra by implementing a custom `SessionProvider` that looks up the Cassandra contact points in the `ServiceLocator` (essentially a DNS SRV query in Kubernetes) and uses the results to build the Cassandra `Session`. That means that by the time the driver is initialized, it is getting a list of resolved `InetSocketAddress` instances (essentially IP:port pairs).

Kubernetes `StatefulSet` does not have the ability to reuse IPs of deleted pods when replacing them (https://github.com/kubernetes/kubernetes/issues/28969). This means that after a shutdown and restart of the Cassandra cluster, the IP addresses that the Cassandra `Session` was built with are stale.

`StatefulSet` pods _do_ have stable host names, but using these doesn't help, either, because the Cassandra driver caches the resolved addresses internally ([JAVA-1522](https://datastax-oss.atlassian.net/browse/JAVA-1522)). Version 4.0 of the driver offers an option to store the unresolved addresses ([JAVA-1978](https://datastax-oss.atlassian.net/browse/JAVA-1978)) if the `Session` is created that way.

We are planning to refactor the session management in Akka Persistence Cassandra by extracting that to Alpakka Cassandra. As part of that work, we also want to integrate support for Akka Service Discovery directly, so that Lagom can use that in the future, and everyone else using Alpakka Cassandra or Akka Persistence Cassandra can also get automatic discovery. However, it will experience the same problem unless we make other changes.

In Akka Persistence Cassandra, once it builds a `Session`, it keeps it and reuses it forever, so AFAICT the only way to get it to re-resolve is to restart the `ActorSystem` (effectively requiring a full service restart in Lagom). Without doing a detailed investigation, I think the cleanest way to solve all of this would be to change our `CassandraSession` wrapper to (optionally?) detect `NoHostAvailableException` failures in the underlying session, then dispose and recreate the session from the `SessionProvider` (and retry executing the statement?)

I also expected the driver to be able to adapt to slow roll-overs of the cluster, but the exact behavior isn't totally clear from the documentation. In any case, as @patriknw said, solving this more generally will also help in that scenario.

I think our best advice for the time being is to avoid running Cassandra in Kubernetes, which still seems to be a fairly immature and troublesome combination.

**Comment by chbatey** [comment]
> Lagom interfaces with Akka Persistence Cassandra by implementing a custom SessionProvider that looks up the Cassandra contact points in the ServiceLocator (essentially a DNS SRV query in Kubernetes) and uses the results to build the Cassandra Session. That means that by the time the driver is initialized, it is getting a list of resolved InetSocketAddress instances (essentially IP:port pairs).

Thanks for the clarification

> I think our best advice for the time being is to avoid running Cassandra in Kubernetes, which still seems to be a fairly immature and troublesome combination.

+100

**Comment by ennru** [comment]
#115 had the same problem with Cassandra in Kubernetes.

**Comment by chbatey** [comment]
We now just rely on the driver configuration for contact points so closing this

**Comment by fezho** [comment]
@chbatey I also got same issue with `gocql`, could you help to point the code changes about this issue?

**Comment by chbatey** [comment]
The driver doesn't support a full set of IP changes for the nodes, only an application restart will fix it

**Comment by chbatey** [comment]
Btw 1.0 of APC uses the latest version of the Cassandra Java Driver which has `advanced.resolve-contact-points` which you can set to false meaning that each new connection will re-resolve. You'll still need to be aware of any DNS caching

**Comment by dpennell** [comment]
Thanks for the notification - we will try to upgrade ASAP.

**Comment by knpatil** [comment]
I have a similar problem with Cassandra deployed in Kubernetes as Statefulsets. While rolling update happening for Cassandra pods, the client which uses datastax java driver is unable to connect and gives up with NoHostAvailableException.

After following on this thread, I am not very clear if there has been any solution on the datastax java driver on this? 

> Btw 1.0 of APC uses the latest version of the Cassandra Java Driver which has `advanced.resolve-contact-points` which you can set to false meaning that each new connection will re-resolve. You'll still need to be aware of any DNS caching

Which version of datastax driver has this feature? Any specific configuration needed while using that version? What is APC @chbatey  ? Thanks.

What is the general pattern of deploying Cassandra in Kubernetes which resolves this issue ? Thanks for your help.
