### ISSUE TITLE
Health check compatible with Akka Management

### ISSUE THREAD

**Issue by chbatey** [akka/akka-persistence-cassandra#554]
Provide a health check that is compatible with https://doc.akka.io/docs/akka-management/current/healthchecks.html to allow users to check the connection to C* is healthy.

A prerequisite is using the same connection for all parts of the journal (planned for 1.0).

**Comment by ennru** [comment]
Would there be a good way to provide this from the imagined new Alpakka Cassandra module?

**Comment by chbatey** [comment]
Yes I think it can be part of the Session. Or just exposing the session that all parts of the plugin use so that they are testing the right connection.

**Comment by jewertow** [comment]
What did you expect from the connection health check? 
Would the query `SELECT now() FROM system.local` be enough to determine the connection is healthy?
I would implement this. What do you think?

**Comment by chbatey** [comment]
Yep and perhaps make the query configurable? system.local isn't replicated so it's a good quick query to check connectivity. Other uses might prefer a health check with a query on a normally replicated table

**Comment by jewertow** [comment]
@chbatey @patriknw I need your advice on implementation. 
My proposal is:
Since the health check compatible with akka-management can accept as an argument only an `ActorSystem`, then the object performing the database query could only be an actor, because from actor system we have access only to actors. 
So I think we can provide the actor that would accept an interface `HealthCheckQuery` with default implementation `SystemLocalHealthCheckQuery` that performs the query `SELECT now() FROM system.local` and users could provide custom implementations. 
The actor performing the query could look like this:
```
object HealthCheckExecutor {
  case object PerformQuery
  def props(query: HealthCheckQuery) = 
    Props(new HealthCheckExecutor(query), "akka-persistence-health-check")
}
class HealthCheckExecutor(query: HealthCheckQuery) extends Actor {
  override def receive = {
    // the sender is a health check compatible with akka-management
    case PerformQuery => query.execute().pipeTo(sender)
  }
}
```
Then on startup users would spawn an actor:
```
system.actorOf(HealthCheckExecutor.props(new SystemLocalHealthCheckQuery))
```
And provided akka-management compatible health check would look like this:
```
class AkkaPersitenceHealthCheck(system: ActorSystem) extends (() => Future[Boolean]) {
  override def apply(): Future[Boolean] = {
    val executorActor = // system.actorSelection.resolveOne and so on
    executorActor ? HealthCheckExecutor.PerformQuery
  }
}
```
This is only a sneak peak rather than a final implementation. What do you think abut the idea?

**Comment by jewertow** [comment]
@patriknw your idea seems good, but how user could create custom health check query?

**Comment by patriknw** [comment]
1. Could be good to put the cql for it config. Would that be enough or did you have something more in mind?
2. Yes, CassandraJournal

**Comment by jewertow** [comment]
@patriknw 
Thank you for your time spent on reviewing my code. It was really exciting to contribute to akka-persistence-cassandra. Your regular code review was really encouraging.

**Comment by patriknw** [comment]
Thank you for contributing!
