### ISSUE TITLE
rewrite RowIterator

### ISSUE THREAD

**Issue by patriknw** [akka/akka-persistence-cassandra#75]
In https://github.com/akka/akka-persistence-cassandra/pull/74 I have removed almost all blocking calls.

The remaining blocking is in the RowIterator that is used for loading snapshot metadata and the RowIterator that is used when deleting events (ReadLowestSequenceNr). That blocking is now contained by a separate dispatcher, but it would be good to rewrite the RowIterators.

**Comment by p-kozlov** [comment]
@patriknw by rewriting iterator and removing blocking from it do you mean replacing iterators with observables? Or akka streams?
Iterator is always blocking by it's nature - there is not way to implement scala.collection.Iterator which is non-blocking. Only if replace Iterator[T] with Iterator[Future[T]] ?

**Comment by p-kozlov** [comment]
The problem which I see here.
Suppose I have future of session + future of prepared statement. I can get Future[java.util.Iterator[Row]]
```for {
  ses <- session.underlying()
   prepSelectMessages <- preparedSelectMessages
} yield ses.execute(...)```

But if I implement it inside scala iterator, hasNext should return Boolean, not Future[Boolean] - there is no way to avoid blocking here.

The design is not perfect from the beginning - perhaps it's better to rewrite these iterators from scratch (without using iterators) instead of trying to optimize iterators to make the non-blocking.

**Comment by patriknw** [comment]
Yeah, the remaining two iterators must go away. We should do it with streams, similar to what we have done for the queries. Another inspiration might be Lagom's stream based `select` that I wrote a while ago: https://github.com/lagom/lagom/blob/master/persistence/src/main/scala/com/lightbend/lagom/internal/persistence/cassandra/CassandraSessionImpl.scala#L217

**Comment by p-kozlov** [comment]
@patriknw please take a loot at this https://github.com/akka/akka-persistence-cassandra/pull/91
I have rewritten the RowIterator (completely removed class, replaced metadata method with Future.flatMap with recursive function). By the way, iterate function is not tail-recursive because the call is inside flatMap, I hope it should not be a problem.
Have no idea how to write the same thing with streams or high-order functions.

If you have better idea, would be great to hear. If it's fine, I can try to rewrite another iterator the same way.

**Comment by patriknw** [comment]
I have implemented this in a simpler way in https://github.com/akka/akka-persistence-cassandra/pull/170
