### ISSUE TITLE
Alternative query for Projections

### ISSUE THREAD

**Issue by patriknw** [akka/akka-persistence-cassandra#823]
I had this idea that maybe it's possible to have a query for all events for a slice of all persistenceIds. That is what Projections typically need.

It would be based on `allPersistenceIds` and `currentEventsByPersistenceId`.

Advantages:
* tagging not needed (simplifies user code)
* tagging is costly with Cassandra (data duplication, more writes) and some events may be lost or duplicated in some error edge cases
* easier to implement direct replication (no queries for normal case)
* possible to adjust number of Projection instances afterwards

Disadvantages:
* the offset becomes large since it must include seqNr for each persistenceId
* might be slow to scan through all persistenceIds

Rough implementation sketch:
```
  implicit val ec: ExecutionContext = ???
  type PersistenceId = String
  type SeqNr = Long
  final case class NextPersistenceId(pid: PersistenceId, seqNr: SeqNr, events: Vector[PersistentRepr])
  final case class UpdatePersistenceIdOffset(pid: PersistenceId, seqNr: SeqNr)
  implicit val askTimeout: Timeout = 10.seconds

  final case class AllEventsOffset(offsets: Map[PersistenceId, SeqNr]) extends Offset

  def allEvents(
      matchingPersistenceId: PersistenceId => Boolean,
      offset: AllEventsOffset): Source[EventEnvelope, NotUsed] = {

    // Spawn actor that keeps track of all matching persistence ids.
    // It runs a persistenceIds query and can sort them in a smart way so that persistenceIds that are recently
    // used are queried more frequently.
    // It can subscribe to pub-sub for direct replication of PersistentRepr, and then queries are not needed
    // for the normal case.
    val persistenceIdsState: ActorRef = ???

    def findAndEmitEvents(pid: PersistenceId, seqNr: SeqNr): Source[EventEnvelope, NotUsed] = {
      currentEventsByPersistenceId(pid, seqNr + 1, Long.MaxValue).alsoTo(Sink.lastOption.mapMaterializedValue {
        lastFut =>
          // when the persistenceIdsState actor has handed out a persistenceId it will not emit that again until
          // it receives the updated seqNr
          lastFut.map {
            case None       => persistenceIdsState ! UpdatePersistenceIdOffset(pid, seqNr)
            case Some(last) => persistenceIdsState ! UpdatePersistenceIdOffset(last.persistenceId, last.sequenceNr)
          }
          NotUsed
      })
    }

    def emitEvents(events: Vector[PersistentRepr]): Source[EventEnvelope, NotUsed] = {
      val last = events.last
      persistenceIdsState ! UpdatePersistenceIdOffset(last.persistenceId, last.sequenceNr)
      Source(
        events.map(
          repr =>
            EventEnvelope(
              Offset.sequence(repr.sequenceNr),
              repr.persistenceId,
              repr.sequenceNr,
              repr.payload,
              repr.timestamp)))
    }

    Source.repeat("")
      .ask[NextPersistenceId](1)(persistenceIdsState)
      .throttle(10, 1.second)
      .flatMapConcat {
        case NextPersistenceId(pid, seqNr, events) =>
          if (events.isEmpty)
            findAndEmitEvents(pid, seqNr)
          else
            emitEvents(events)
      }
  }
```

**Comment by octonato** [comment]
Maybe this is something we could implement in Projection as a `SourceProvider`?

**Comment by octonato** [comment]
I have drafted some ideas on paper on how we could eliminate the use of tags or at least reduce the eventual consistency delay. 

What I had in mind was to start a projection child actor with the EventSourced behavior that queries the journal by persistence id. 

* an entity is started and the companion projection starts as a child (can have one or more of those)
* first step for the companion projection is to catch-up with the journal (`eventsByPersistenceId`), if needed
* then, after that it can get the events directly from the EventSourced behavior, in-memory (no PubSub) and async. Similar to the replicated ES.  
* the companion projection should buffer incoming events from the entity and swap the stream when it detects that buffer and query is overlapping. Then we can stop hitting the db and consume from buffer.

The lifecycle of the companion projection is bound to the lifecycle of the running EventSourcedBehavior. When it passivates, the projection passivates. We can make sure it consumes it's in-memory buffer before everything stops.

Then of course, we can always loose events in case of a crash. So the projection can run behind and will only catch-up when the entity starts again.

The ProjectionId would be "projection-name" + "entity-id".

My initial idea was to have a `ShardedDaemon` checking the offset-store to see if there are projections  running behind. When it detects something, it hits the entity to trigger the projection catch-up. 

The disadvantage here is that it will start the entity, possibly loading snapshots, replaying events, while the intention is to trigger the projection catch-up. We can see how to improve it.

In my head, we still needed the tags, but the query proposed here would eliminate it. The fact that it could be slow becomes a non-issue because the daemon is not the primary responsible for the projection to run. It's there to ensure the catch-up. The offset won't grow in side either, because it won't be a map. Each entity will have it's own offset:  "projection-name" + "entity-id"

**Comment by octonato** [comment]
Maybe the idea of having the companion projection as a child is not a good one. I would like to avoid serialization and network, but it may be simple to have it running as an independent actor. 

The daemon won't force an entity start if it needs to bootstrap the projection to trigger a catch-up. 

Things become also less tangled, which has its advantage.

**Comment by octonato** [comment]
btw, should we move this issue to https://github.com/akka/akka-projection?

**Comment by patriknw** [comment]
I think that having a projection instance (child actor or elsewhere) per persistenceId is too far from our original design of Projections. I'm suggesting the same granularity as with tags but without tags. See draft proposal in https://github.com/akka/akka-persistence-cassandra/pull/836

**Comment by patriknw** [comment]
This idea is superseded by the eventsBySlices and the projection implementation in https://github.com/akka/akka-persistence-r2dbc
