### ISSUE TITLE
Error causes events by tag stream to skip events

### ISSUE THREAD

**Issue by dope9967** [akka/akka-persistence-cassandra#824]
### Versions used 

Akka version: 2.6.4
Akka Persistence Cassandra Version: 0.103
Lagom version: 1.6.2

### Expected Behavior

Events by tag stream shouldn't skip events no matter what error gets thrown by the journal.

### Actual Behavior

Under certain failure condition, events by tag stream skipped over events. Skipping seemed to only happened for an active stream - a running Lagom's read-side and topic producer. Rebooting service didn't fix it, because offset already advanced beyond event in error. Resetting offset helped, because messages, tag_views and tag_write_progress weren't corrupted. What might be unique for this scenario is that events and state for this entity use `AsyncSerializer`, which does calls to another service for GDPR related functionality, and cluster was having latency issues with internal networking when this issue occurred. Skipping happened for several different entities running in several different services.

### Relevant logs
Logs from Datadog, replaced some sensitive data with placeholders:
```
date,Host,Service,message
2020-10-02T16:51:06.337Z,i-0ce9a860b46a79985,service,"received TagWrite but actor not active (dropping, will be resolved when actor restarts): [Entity|PersistenceId1]"
2020-10-02T16:51:05.445Z,i-04dac8984ca0901f2,service,"Persist of [akka.persistence.journal.Tagged] failed in [com.example.Entity] with id [PersistenceId1], caused by: {Circuit Breaker Timed out."
2020-10-02T16:51:05.445Z,i-04dac8984ca0901f2,service,"Topic subscription interrupted due to failure: [com.lightbend.lagom.scaladsl.persistence.PersistentEntity$PersistException: Persist of [akka.persistence.journal.Tagged] failed in [com.example.Entity] with id [PersistenceId1], caused by: {Circuit Breaker Timed out.]"
2020-10-02T16:51:05.423Z,i-0ce9a860b46a79985,service,Failed to persist event type [akka.persistence.journal.Tagged] with sequence number [1] for persistenceId [Entity|PersistenceId1].
```

### Reproducible Test Case

If the issue is hard to identify, I could try to reproduce it in an example project.

**Comment by chbatey** [comment]
Hi @dope9967 thanks for reporting. I don't think we need a reproducer as I think I understand the scenario:

* Event written to messages then the actor crashes due to its next event timeout out on a write (it must be the next one as we don't send the event to the tag writing system until this has passed)
* Same event not written to tag_views as the persistent actor has stopped (it does this as it expects the persistent actor to fix it when it starts up, potentially on a different node)
* Offset is moved on past the event by the time it is written to tag_views

This case is meant to be handled by back tracking: https://doc.akka.io/docs/akka-persistence-cassandra/0.103/events-by-tag.html#back-tracking and/or eventual consistency delay: https://doc.akka.io/docs/akka-persistence-cassandra/0.103/events-by-tag.html#consistency

Do you know when the event made it into the tag_views?

**Comment by dope9967** [comment]
Hey @chbatey, thanks for prompt reply! Sadly, I don't know when the event made it to the tag views - didn't monitor the system live myself and there were no logs for that. If I understood you correctly, this means that if the system is kept running in reduced performance, it's quite possible for read-sides to skip over events - they do not wait forever, and after the max wait period they only check within certain range, which is limited to current or previous time bucket, correct? Though time bucket size being default, one hour, would mean that tag write had to be seriously delayed.

**Comment by chbatey** [comment]
That's right. The only case it doesn't go back that far is if the events by tag is restarted from a later offset. Whatever offset you start from is the upper limit for any back track.

**Comment by dope9967** [comment]
Understood. So I'll close this issue - got to compensate for this behavior in application itself.
